### ISSUE TITLE
Error!!!! in kernal _Spyder

### ISSUE THREAD

**Issue by Chandula529** [imarranz/namecolor_to_rgb#1]
When I run the code it shows an error in the Kernal. 
![image](https://github.com/imarranz/namecolor_to_rgb/assets/136285202/0e8e04a4-b1c0-4114-ba86-139c9cfadb24)
![image](https://github.com/imarranz/namecolor_to_rgb/assets/136285202/7e018d79-18fc-41a0-8c0d-b4767a380fb1)

**Comment by imarranz** [comment]
Hi,

Thank you for reaching out with the details of the error you're experiencing. It appears that your Python environment does not have the `matplotlib` library installed, or there was an issue importing it. This is why the Spyder console could not be initiated.

To resolve this issue, you can install `matplotlib` using either pip or conda, depending on your setup. Here are the instructions for both methods:

**If you are using pip:**

1. Open your command prompt or terminal.
2. Type the following command and press Enter:
   ```
   pip install matplotlib
   ```

**If you are using conda:**

1. Open your Anaconda Prompt or terminal.
2. Type the following command and press Enter:
   ```
   conda install matplotlib
   ```

After installing `matplotlib`, please restart Spyder and try opening the console again. This should resolve the issue. If you continue to experience problems or have any other questions, please do not hesitate to contact me.
